spring:
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.context.MessageSourceAutoConfiguration,org.springframework.boot.autoconfigure.webservices.WebServicesAutoConfiguration"
logging:
  level:
    root: info
    org.apereo.cas: debug
    org.relections: info
    org.springframework: info
    org.apereo.cas.authentication: trace
